"""Planner defaults and keyword heuristics when Gemini returns non-JSON."""

from __future__ import annotations


def default_wide_tool_plan() -> list[dict]:
    return [
        {"tool": "cluster_health_summary", "arguments": {}},
        {"tool": "map_cluster_topology", "arguments": {}},
        {"tool": "diagnose_service_routing", "arguments": {}},
        {"tool": "audit_cluster_policies", "arguments": {}},
        {"tool": "check_resource_quotas_compliance", "arguments": {}},
        {"tool": "check_pod_disruption_budgets", "arguments": {}},
        {"tool": "aws_cost_overview", "arguments": {}},
        {"tool": "aws_cost_by_service", "arguments": {}},
        {"tool": "aws_cost_forecast", "arguments": {}},
        {"tool": "cost_anomaly_detection", "arguments": {}},
        {"tool": "list_pods", "arguments": {}},
        {"tool": "list_deployments", "arguments": {}},
        {"tool": "list_stateful_sets", "arguments": {}},
        {"tool": "list_daemon_sets", "arguments": {}},
        {"tool": "list_cron_jobs", "arguments": {}},
        {"tool": "list_jobs", "arguments": {"limit": 120}},
        {"tool": "list_services", "arguments": {}},
        {"tool": "list_endpoints", "arguments": {}},
        {"tool": "list_ingresses", "arguments": {}},
        {"tool": "list_namespaces", "arguments": {}},
        {"tool": "list_nodes", "arguments": {}},
        {"tool": "list_events", "arguments": {}},
        {"tool": "list_horizontal_pod_autoscalers", "arguments": {}},
        {"tool": "list_pvcs", "arguments": {}},
        {"tool": "list_pvs", "arguments": {}},
        {"tool": "list_storage_classes", "arguments": {}},
        {"tool": "list_resource_quotas", "arguments": {}},
        {"tool": "list_limit_ranges", "arguments": {}},
        {"tool": "list_argocd_applications", "arguments": {}},
        {"tool": "finops_cluster_signals", "arguments": {}},
        {"tool": "prometheus_common_metrics", "arguments": {}},
    ]


KUBERNETES_KEYWORDS = [
    "cluster",
    "kube",
    "k8s",
    "kubernetes",
    "pod",
    "pods",
    "deployment",
    "deployments",
    "stateful",
    "daemon",
    "cron",
    "job",
    "hpa",
    "autoscal",
    "service",
    "services",
    "ingress",
    "argocd",
    "application",
    "applications",
    "gitops",
    "cost",
    "billing",
    "forecast",
    "amortized",
    "unblended",
    "chargeback",
    "allocation tag",
    "cost explorer",
    "optimize",
    "optimization",
    "right-size",
    "resource",
    "memory",
    "cpu",
    "node",
    "nodes",
    "namespace",
    "prometheus",
    "monitoring",
    "metrics",
    "logs",
    "events",
    "health",
    "incident",
    "outage",
    "latency",
    "endpoints",
    "connectivity",
    "traffic",
    "routing",
    "dependency",
    "dependencies",
    "topology",
    "graph",
    "relationship",
    "relationships",
    "root cause",
    "network",
    "pvc",
    "persistent",
    "storage",
    "volume",
    "quota",
    "limitrange",
    "sandbox",
    "workload",
    "finops",
    "budget",
    "spend",
    "tag",
    "tags",
    "savings",
    "waste",
    "crash",
    "crashloop",
    "rollout",
    "configmap",
    "troubleshoot",
    "restart",
    "imagepull",
    "pending",
]
